### ISSUE TITLE
Tagforce TMS

### ISSUE THREAD

**Issue by zeak6464** [xan1242/ehppack#1]
I've used this tool , but cant seem to find anything to open Tag Force TMS files. 
[cutin-chara-amunael01-base.zip](https://github.com/xan1242/ehppack/files/7072846/cutin-chara-amunael01-base.zip)

**Comment by xan1242** [comment]
TMS files are models. You'd need another tool to read or convert those to a usable format. Maybe a MaxScript for 3DS Max could be written for them. 

I'm not much of an expert in models myself but it seems like a relatively simple format to decipher (lots of floats, probably verticies and normals). I could try some things out (convert floats to OBJ and hope for the best) but again, I'm a total noob when it comes to model formats.

In any case, this is something that will need to be done with a separate tool. A good place to ask around would probably be ZenHAX forum.

**Comment by zeak6464** [comment]
I have tried to asked there but no luck either. Thank you tho.
